#+title:     ft_irc working notes
#+author:    Chris Haikney
#+email:     chaikney@student.42urduliz.com

#+TODO: TODO NEXT WAIT | DONE FAIL

* Form team

** DONE Make GH repo

** TODO Look for 3rd person

* Specification and other resources
"IRC client-server connections work over TCP/IP. The standard ports for client-server connections are TCP/6667 for plaintext, and TCP/6697 for TLS connections."
The most useful documents seem to be:
- [[https://modern.ircdocs.horse/][IRC Client Protocol Specification]]
  This is very clear, but goes too far / modern
- https://tools.ietf.org/html/rfc1459
  This is the official RFC. Old, possibly harder to understand (I haven't read it yet) but probably the last word in evaluations.
- [[http:https://github.com/ircdocs/parser-tests][Parser tools]]
  Checkers for parsing, possibly useful but require some setup.

* Classes and key concepts
Users send messages to channels on a server
** Server
- listens on port 6667 (plaintext) and 6697 (TLS)
- allows users to register
  In addition to the nickname, all servers must have the following information about all clients: the real name/address of the host that the client is connecting from, the username of the client on that host, and the server to which the client is connected.
- receives messages from authorised users
- acts on those messages
- keeps track of known channels / rooms
- "Servers SHOULD pick a name which contains a dot character (".", 0x2E). This can help clients disambiguate between server names and nicknames in a message source."
** User (also known as client)
Note that clients will be sending out server things, so we only have send things back to them, not worry about *how* they (clients) behave...
" anything connecting to a server that is not another server. Each client is distinguished from other clients by a unique nickname. "
- registers a nickname on a server
 #+begin_quote
  "Nicknames are non-empty strings with the following restrictions:

    They MUST NOT contain any of the following characters: space (' ', 0x20), comma (',', 0x2C), asterisk ('*', 0x2A), question mark ('?', 0x3F), exclamation mark ('!', 0x21), at sign ('@', 0x40).
    They MUST NOT start with any of the following characters: dollar ('$', 0x24), colon (':', 0x3A).
    They MUST NOT start with a character listed as a channel type, channel membership prefix, or prefix listed in the IRCv3 multi-prefix Extension.
    They SHOULD NOT contain any dot character ('.', 0x2E).

  Servers MAY have additional implementation-specific nickname restrictions and SHOULD avoid the use of nicknames which are ambiguous with commands or command parameters where this could lead to confusion or error."
 #+end_quote
- joins or creates channels
- has various levels of abilities, which differ according to the channel
- what is a **client mask**?
  It is referred to a lot in relation, e.g. to channel modes. Sounds like something we need to have defined as a struct or subclass of client.
** Channel (also known as room)
https://modern.ircdocs.horse/#channels
"a named group of one or more clients. The channel is created implicitly when the first client joins it, and the channel ceases to exist when the last client leaves it. While the channel exists, any client can reference the channel using the name of the channel. Networks that support the concept of ‘channel ownership’ may persist specific channels in some way while no clients are connected to them."
Sort of implies that the simplest representation of this would be a [container] of clients, plus some shared info of the channel (e.g. those modes below)
- Types of channel
  - The first standard type of channel is a regular channel, which is known to all servers that are connected to the network. The prefix character for this type of channel is ('#', 0x23).
  - The second type are server-specific or local channels, where the clients connected can only see and talk to other clients on the same server. The prefix character for this type of channel is ('&', 0x26). Other types of channels are described in the Channel Types section."
- Channel modes
  https://modern.ircdocs.horse/#channel-modes
  "Along with various channel types, there are also channel modes that can alter the characteristics and behaviour of individual channels. See the Channel Modes section for more information on these."
  This includes things like ban; some of these are set by default so we should set them up on channel creation.

- has some rules for its name
  "Channel names are strings (beginning with specified prefix characters). Apart from the requirement of the first character being a valid channel type prefix character; the only restriction on a channel name is that it may not contain any spaces (' ', 0x20), a control G / BELL ('^G', 0x07), or a comma (',', 0x2C) (which is used as a list item separator by the protocol)."
- also has a subject line
- is used to direct messages to users
  All clients in the channel will receive all messages addressed to that channel.
** Messages (for sending or for commands)
https://modern.ircdocs.horse/#message-format
#+begin_quote
An IRC message is a single line, delimited by a pair of CR ('\r', 0x0D) and LF ('\n', 0x0A) characters.

    When reading messages from a stream, read the incoming data into a buffer. Only parse and process a message once you encounter the \r\n at the end of it. If you encounter an empty message, silently ignore it.
    When sending messages, ensure that a pair of \r\n characters follows every single message your software sends out.
#+end_quote
So read until we reach the end pair *or* some safety limit that we set. ("Most IRC servers limit messages to 512 bytes in length, including the trailing CR-LF characters.")
The parts of messages (each separated by one more more space 0x20) are then:
- tags ("optional, and MUST NOT be sent unless explicitly enabled by a capability.")
  So ignore this for now
- source  (or prefix)
  Indicated by : aka 0x3A
  Assuming no tags this *must* be the first char of the message
- command
  "The command must either be a valid IRC command or a numeric (a three-digit number represented as text)."
- parameters
Seems pretty fundamental that we have strong parsing of messages. What format do they have? And what do we have to extract, store and process from them?
** Services -- no longer used, can be ignored

* Important processes / methods

** User registration -- probably lives within the server
https://modern.ircdocs.horse/#connection-registration
Assuming we put aside for now Capability Negotiation, then only *the first 3* of these are needed, and the 3 commands should be part of the connection request that we receive / process.
#+begin_quote
Immediately upon establishing a connection the client must attempt registration, without waiting for any banner message from the server.

Until registration is complete, only a limited subset of commands SHOULD be accepted by the server. This is because it makes sense to require a registered (fully connected) client connection before allowing commands such as JOIN, PRIVMSG and others.

The recommended order of commands during registration is as follows:

    CAP LS 302
    PASS
    NICK and USER
    Capability Negotiation
    SASL (if negotiated)
    CAP END

The commands specified in steps 1-3 should be sent on connection. I
#+end_quote
On success, the server sends RPL_WELCOME, including the full client identifier that we used.
** Message parsing -- almost certainly a Server method

*** Validate and direct the command after parsing

*** Execute the command with parsing

** Message sending -- almost certainly a Server method

* Learn about network connections in C++
** Server-side connection process steps
https://www.geeksforgeeks.org/cpp/socket-programming-in-cpp/
Note the server-side piece.
1. Create server socket using socket()
2. define the server address
  #+begin_src
serverAddress.sin_family = AF_INET;
serverAddress.sin_port = htons(8080);
serverAddress.sin_addr.s_addr = INADDR_ANY;
  #+end_src
#+begin_quote
    htons(): Converts port to network byte order.
    INADDR_ANY: Accept connections on any IP.
here,
    sockaddr_in: It is the data type that is used to store the address of the socket.
    htons(): This function is used to convert the unsigned int from machine byte order to network byte order.
    INADDR_ANY: It is used when we don't want to bind our socket to any particular IP and instead make it listen to all the available IPs.
#+end_quote
3. bind socket to address
  #+begin_src
bind(serverSocket, (struct sockaddr*)&serverAddress, sizeof(serverAddress));
  #+end_src
4. listen for incoming connections
  #+begin_src
listen(serverSocket, 5);
  #+end_src
5. Accept client connection
   ...then we have to think about *how many* of these connections will we have at once? Is each connection a new client and new user?
   It implies the beginning of the registration process
  src_c[:exports code]{int clientSocket = accept(serverSocket, nullptr, nullptr);}
  6. receive data from client
     I guess this goes on the whole time that the socket is open? Or the connection.
     Do we have one socket per client? One connection per client? How does this fit together?
    #+begin_src
char buffer[1024] = {0};
recv(clientSocket, buffer, sizeof(buffer), 0);
cout << "Message from client: " << buffer << endl;
    #+end_src
  7. Close server socket
     ...I guess when the client logs off? Or when they time out? How does this relate to "keep alive" and all that?
    src_c[:exports code]{close(serverSocket);}
** Semantics and syntax of calls needed
*** socket()
Creates a socket.
There are 2 types: TCP (for this) and UDP.
#+begin_src
#include <sys/socket.h>
       int socket(int domain, int type, int protocol);
#+end_src
domain = AF_INET for IP4 or possibly AF_INET6 for IPv6 (both?)
type = SOCK_STREAM ... as far as I can tell. "a full-duplex byte stream"
protocol = probably 0. "Normally only a single protocol exists to support a particular socket type within  a  given protocol  family,  in  which  case protocol can be specified as 0."

On success, listen() returns a file descriptor for the connection.
If it fails you get -1 and a value for ERRNO to handle (I assume we would set up exceptions for this)
*** listen()
is this socket free?
*** accept()
take a connection on that socket / port / whatever
** How to pass messages to a server?
there is a file descriptor, so maybe yes?
Would be useful for testing.
The subject document says use `nc` to test partial and malformed message handling.
src_shell[:exports code]{nc localhost 6667}
* Tasks to be done for IRC project

** Make a diagram of the classes

** Get a list of *all* the commands that the server should be able to handle
...and then we can think about how to implement them. (What are the most important?)

*** Connection messages -- implement these first

**** CAP
This can be ignored I think. Recognise it and silently drop it for client compatibility.
Full description: https://ircv3.net/specs/extensions/capability-negotiation.html
Although the actual standard capabilities are at: https://ircv3.net/registry#capabilities
...would we know any of those?

**** NEXT PASS
*Must* be the first thing received from a client
PASS <password>
If there is a problem:
- ERR_NEEDMOREPARAMS (461)
- ERR_ALREADYREGISTRED (462)
- ERR_PASSWDMISMATCH (464)
**** NICK
NICK Jimmy
...the simple form for a newly-registered user.
There might also be a more complicated form for the "registered user changing nick" case.
           ERR_NONICKNAMEGIVEN             ERR_ERRONEUSNICKNAME
           ERR_NICKNAMEINUSE               ERR_NICKCOLLISION
           ERR_UNAVAILRESOURCE             ERR_RESTRICTED
There are restrictions on characters in the nickname:
#+begin_quote
Servers MUST allow at least all alphanumerical characters, square and curly brackets ([]{}), backslashes (\), and pipe (|) characters in nicknames, and MAY disallow digits as the first character. Servers MAY allow extra characters, as long as they do not introduce ambiguity in other commands, including:
    no leading # character or other character advertized in CHANTYPES
    no leading colon (:)
    no ASCII space
#+end_quote
ERR_ERRONEUSNICKNAME is the response if the nickname is forbidden that way.

**** USER
   Command: USER
   Parameters: <user> <mode> <unused> <realname>

   The USER command is used at the beginning of connection to specify
   the username, hostname and realname of a new user.

   The <mode> parameter should be a numeric, and can be used to automatically set user modes when registering with the server.  This parameter is a bitmask, with only 2 bits having any signification: if the bit 2 is set, the user mode 'w' will be set and if the bit 3 is set, the user mode 'i' will be set.  (See Section 3.1.5 "User Modes").
   The <realname> may contain space characters.

   If there is a problem, same as PASS:
   - ERR_NEEDMOREPARAMS
   - ERR_ALREADYREGISTRED


**** ERROR
- Command: ERROR
- Parameters: <reason>

This message is sent from a server to a client to report a fatal error, before terminating the client’s connection. This MUST only be used to report fatal errors. Regular errors should use the appropriate numerics or the IRCv3 standard replies framework.
**** QUIT
- Command: QUIT
- Parameters: [<reason>]

The QUIT command is used to terminate a client’s connection to the server. The server acknowledges this by replying with an ERROR message and closing the connection to the client.
When connections are terminated by a client-sent QUIT command, servers SHOULD prepend <reason> with the ASCII string "Quit: " when sending QUIT messages to other clients, to represent that this user terminated the connection themselves.
*** Channel operations

**** JOIN

**** PART

**** TOPIC

**** NAMES

**** LIST

**** INVITE

**** KICK

**** MODE

*** Sending messages

**** PRIVMSG

**** NOTICE
Ignorable?

*** Numeric equivalents of the commands
Three digits represented as text
https://modern.ircdocs.horse/#numerics
https://defs.ircdocs.horse/
** DONE Parse a command string into a struct / class
Read buffer until reaching crlf, i.e. \r\n, 0x0D 0x0A
(stringstream getline?)
- if the first char is @ process as tags
  i.e. ignore it, should not have been sent
- if the first char is : process as source
 NOTE clients should not send this. So we can / should add it ourself based on the client it came from. Docs site gives option for source, nick, user. I don't really understand it.
 So for now all we need to do is make sure it can be safely skipped.
- the next part is a command
  The command must either be a valid IRC command or a numeric (a three-digit number represented as text).
  store a string

- from the next space until the end are the parameters
  There can be any number of them, though no more than 15.
  What storage container to use for that? list? map?

** Error messages / enums to be sent
Put in a header file? Or what other option?
https://defs.ircdocs.horse/
https://www.alien.net.au/irc/ -- very old but has the definitions in a maybe-usable format

*** Replies from RFC document
5.1 Command responses

   Numerics in the range from 001 to 099 are used for client-server connections only and should never travel between servers.  Replies generated in the response to commands are found in the range from 200 to 399.

       001    RPL_WELCOME
              "Welcome to the Internet Relay Network
               <nick>!<user>@<host>"
       002    RPL_YOURHOST
              "Your host is <servername>, running version <ver>"
       003    RPL_CREATED
              "This server was created <date>"
       004    RPL_MYINFO
              "<servername> <version> <available user modes>
               <available channel modes>"

         - The server sends Replies 001 to 004 to a user upon successful registration.

       005    RPL_BOUNCE
              "Try server <server name>, port <port number>"

         - Sent by the server to a user to suggest an alternative server.  This is often used when the connection is refused because the server is already full.

       302    RPL_USERHOST
              ":*1<reply> *( " " <reply> )"

         - Reply format used by USERHOST to list replies to the query list.  The reply string is composed as follows:

           reply = nickname [ "*" ] "=" ( "+" / "-" ) hostname

           The '*' indicates whether the client has registered as an Operator.  The '-' or '+' characters represent whether the client has set an AWAY message or not respectively.

       303    RPL_ISON
              ":*1<nick> *( " " <nick> )"

         - Reply format used by ISON to list replies to the query list.

       301    RPL_AWAY
              "<nick> :<away message>"
       305    RPL_UNAWAY
              ":You are no longer marked as being away"
       306    RPL_NOWAWAY
              ":You have been marked as being away"

         - These replies are used with the AWAY command (if allowed).  RPL_AWAY is sent to any client sending a PRIVMSG to a client which is away.  RPL_AWAY is only sent by the server to which the client is connected. Replies RPL_UNAWAY and RPL_NOWAWAY are sent when the client removes and sets an AWAY message.

       311    RPL_WHOISUSER
              "<nick> <user> <host> * :<real name>"
       312    RPL_WHOISSERVER
              "<nick> <server> :<server info>"
       313    RPL_WHOISOPERATOR
              "<nick> :is an IRC operator"
       317    RPL_WHOISIDLE
              "<nick> <integer> :seconds idle"
       318    RPL_ENDOFWHOIS
              "<nick> :End of WHOIS list"
       319    RPL_WHOISCHANNELS
              "<nick> :*( ( "@" / "+" ) <channel> " " )"

         - Replies 311 - 313, 317 - 319 are all replies generated in response to a WHOIS message.  Given that there are enough parameters present, the answering server MUST either formulate a reply out of the above numerics (if the query nick is found) or return an error reply.  The '*' in RPL_WHOISUSER is there as the literal character and not as a wild card.  For each reply set, only RPL_WHOISCHANNELS may appear more than once (for long lists of channel names).
           The '@' and '+' characters next to the channel name indicate whether a client is a channel operator or has been granted permission to speak on a moderated channel.  The RPL_ENDOFWHOIS reply is used to mark the end of processing a WHOIS message.

       314    RPL_WHOWASUSER
              "<nick> <user> <host> * :<real name>"
       369    RPL_ENDOFWHOWAS
              "<nick> :End of WHOWAS"

         - When replying to a WHOWAS message, a server MUST use the replies RPL_WHOWASUSER, RPL_WHOISSERVER or ERR_WASNOSUCHNICK for each nickname in the presented list.  At the end of all reply batches, there MUST be RPL_ENDOFWHOWAS (even if there was only one reply and it was an error).

       321    RPL_LISTSTART
              Obsolete. Not used.

       322    RPL_LIST
              "<channel> <# visible> :<topic>"
       323    RPL_LISTEND
              ":End of LIST"

         - Replies RPL_LIST, RPL_LISTEND mark the actual replies with data and end of the server's response to a LIST command.  If there are no channels available to return, only the end reply MUST be sent.
       325    RPL_UNIQOPIS
              "<channel> <nickname>"

       324    RPL_CHANNELMODEIS
              "<channel> <mode> <mode params>"

       331    RPL_NOTOPIC
              "<channel> :No topic is set"
       332    RPL_TOPIC
              "<channel> :<topic>"

         - When sending a TOPIC message to determine the channel topic, one of two replies is sent.  If the topic is set, RPL_TOPIC is sent back else RPL_NOTOPIC.

       341    RPL_INVITING
              "<channel> <nick>"

         - Returned by the server to indicate that the attempted INVITE message was successful and is being passed onto the end client.

       342    RPL_SUMMONING
              "<user> :Summoning user to IRC"

         - Returned by a server answering a SUMMON message to indicate that it is summoning that user.

       346    RPL_INVITELIST
              "<channel> <invitemask>"
       347    RPL_ENDOFINVITELIST
              "<channel> :End of channel invite list"

         - When listing the 'invitations masks' for a given channel, a server is required to send the list back using the RPL_INVITELIST and RPL_ENDOFINVITELIST messages.  A separate RPL_INVITELIST is sent for each active mask. After the masks have been listed (or if none present) a RPL_ENDOFINVITELIST MUST be sent.

       348    RPL_EXCEPTLIST
              "<channel> <exceptionmask>"
       349    RPL_ENDOFEXCEPTLIST
              "<channel> :End of channel exception list"
         - When listing the 'exception masks' for a given channel, a server is required to send the list back using the RPL_EXCEPTLIST and RPL_ENDOFEXCEPTLIST messages.  A separate RPL_EXCEPTLIST is sent for each active mask. After the masks have been listed (or if none present) a RPL_ENDOFEXCEPTLIST MUST be sent.

       351    RPL_VERSION
              "<version>.<debuglevel> <server> :<comments>"

         - Reply by the server showing its version details. The <version> is the version of the software being used (including any patchlevel revisions) and the <debuglevel> is used to indicate if the server is running in "debug mode".

           The "comments" field may contain any comments about the version or further version details.

       352    RPL_WHOREPLY
              "<channel> <user> <host> <server> <nick>
              ( "H" / "G" > ["*"] [ ( "@" / "+" ) ]
              :<hopcount> <real name>"

       315    RPL_ENDOFWHO
              "<name> :End of WHO list"

         - The RPL_WHOREPLY and RPL_ENDOFWHO pair are used to answer a WHO message.  The RPL_WHOREPLY is only sent if there is an appropriate match to the WHO query.  If there is a list of parameters supplied with a WHO message, a RPL_ENDOFWHO MUST be sent after processing each list item with <name> being the item.

       353    RPL_NAMREPLY
              "( "=" / "*" / "@" ) <channel>
               :[ "@" / "+" ] <nick> *( " " [ "@" / "+" ] <nick> )
         - "@" is used for secret channels, "*" for private
           channels, and "=" for others (public channels).

       366    RPL_ENDOFNAMES
              "<channel> :End of NAMES list"

         - To reply to a NAMES message, a reply pair consisting of RPL_NAMREPLY and RPL_ENDOFNAMES is sent by the server back to the client.  If there is no channel found as in the query, then only RPL_ENDOFNAMES is returned.  The exception to this is when a NAMES message is sent with no parameters and all visible channels and contents are sent back in a series of RPL_NAMEREPLY messages with a RPL_ENDOFNAMES to mark the end.
       364    RPL_LINKS
              "<mask> <server> :<hopcount> <server info>"
       365    RPL_ENDOFLINKS
              "<mask> :End of LINKS list"

         - In replying to the LINKS message, a server MUST send replies back using the RPL_LINKS numeric and mark the end of the list using an RPL_ENDOFLINKS reply.

       367    RPL_BANLIST
              "<channel> <banmask>"
       368    RPL_ENDOFBANLIST
              "<channel> :End of channel ban list"

         - When listing the active 'bans' for a given channel, a server is required to send the list back using the RPL_BANLIST and RPL_ENDOFBANLIST messages.  A separate RPL_BANLIST is sent for each active banmask.  After the banmasks have been listed (or if none present) a RPL_ENDOFBANLIST MUST be sent.

       371    RPL_INFO
              ":<string>"
       374    RPL_ENDOFINFO
              ":End of INFO list"

         - A server responding to an INFO message is required to send all its 'info' in a series of RPL_INFO messages with a RPL_ENDOFINFO reply to indicate the end of the replies.

       375    RPL_MOTDSTART
              ":- <server> Message of the day - "
       372    RPL_MOTD
              ":- <text>"
       376    RPL_ENDOFMOTD
              ":End of MOTD command"

         - When responding to the MOTD message and the MOTD file is found, the file is displayed line by line, with each line no longer than 80 characters, using RPL_MOTD format replies.  These MUST be surrounded by a RPL_MOTDSTART (before the RPL_MOTDs) and an RPL_ENDOFMOTD (after).

       381    RPL_YOUREOPER
              ":You are now an IRC operator"

         - RPL_YOUREOPER is sent back to a client which has just successfully issued an OPER message and gained operator status.

       382    RPL_REHASHING
              "<config file> :Rehashing"

         - If the REHASH option is used and an operator sends a REHASH message, an RPL_REHASHING is sent back to the operator.
       383    RPL_YOURESERVICE
              "You are service <servicename>"

         - Sent by the server to a service upon successful registration.

       391    RPL_TIME
              "<server> :<string showing server's local time>"

         - When replying to the TIME message, a server MUST send the reply using the RPL_TIME format above.  The string showing the time need only contain the correct day and time there.  There is no further requirement for the
           time string.

       392    RPL_USERSSTART
              ":UserID   Terminal  Host"
       393    RPL_USERS
              ":<username> <ttyline> <hostname>"
       394    RPL_ENDOFUSERS
              ":End of users"
       395    RPL_NOUSERS
              ":Nobody logged in"

         - If the USERS message is handled by a server, the replies RPL_USERSTART, RPL_USERS, RPL_ENDOFUSERS and RPL_NOUSERS are used.  RPL_USERSSTART MUST be sent first, following by either a sequence of RPL_USERS or a single RPL_NOUSER.  Following this is RPL_ENDOFUSERS.

       200    RPL_TRACELINK
              "Link <version & debug level> <destination>
               <next server> V<protocol version>
               <link uptime in seconds> <backstream sendq>
               <upstream sendq>"
       201    RPL_TRACECONNECTING
              "Try. <class> <server>"
       202    RPL_TRACEHANDSHAKE
              "H.S. <class> <server>"
       203    RPL_TRACEUNKNOWN
              "???? <class> [<client IP address in dot form>]"
       204    RPL_TRACEOPERATOR
              "Oper <class> <nick>"
       205    RPL_TRACEUSER
              "User <class> <nick>"
       206    RPL_TRACESERVER
              "Serv <class> <int>S <int>C <server>
               <nick!user|*!*>@<host|server> V<protocol version>"
       207    RPL_TRACESERVICE
              "Service <class> <name> <type> <active type>"
       208    RPL_TRACENEWTYPE
              "<newtype> 0 <client name>"
       209    RPL_TRACECLASS
              "Class <class> <count>"
       210    RPL_TRACERECONNECT
              Unused.
       261    RPL_TRACELOG
              "File <logfile> <debug level>"
       262    RPL_TRACEEND
              "<server name> <version & debug level> :End of TRACE"

         - The RPL_TRACE* are all returned by the server in response to the TRACE message.  How many are returned is dependent on the TRACE message and whether it was sent by an operator or not.  There is no predefined order for which occurs first. Replies RPL_TRACEUNKNOWN, RPL_TRACECONNECTING and RPL_TRACEHANDSHAKE are all used for connections which have not been fully established and are either unknown, still attempting to connect or in the process of completing the 'server handshake'.
           RPL_TRACELINK is sent by any server which handles a TRACE message and has to pass it on to another server.  The list of RPL_TRACELINKs sent in response to a TRACE command traversing the IRC network should reflect the actual connectivity of the servers themselves along that path.

           RPL_TRACENEWTYPE is to be used for any connection which does not fit in the other categories but is being displayed anyway. RPL_TRACEEND is sent to indicate the end of the list.
       211    RPL_STATSLINKINFO
              "<linkname> <sendq> <sent messages>
               <sent Kbytes> <received messages>
               <received Kbytes> <time open>"

         - reports statistics on a connection.  <linkname> identifies the particular connection, <sendq> is the amount of data that is queued and waiting to be sent <sent messages> the number of messages sent, and <sent Kbytes> the amount of data sent, in Kbytes. <received messages> and <received Kbytes> are the equivalent of <sent messages> and <sent Kbytes> for received data, respectively.  <time open> indicates how long ago the connection was opened, in seconds.

       212    RPL_STATSCOMMANDS
              "<command> <count> <byte count> <remote count>"

         - reports statistics on commands usage.

       219    RPL_ENDOFSTATS
              "<stats letter> :End of STATS report"

       242    RPL_STATSUPTIME
              ":Server Up %d days %d:%02d:%02d"

         - reports the server uptime.

       243    RPL_STATSOLINE
              "O <hostmask> * <name>"

         - reports the allowed hosts from where user may become IRC operators.

       221    RPL_UMODEIS
              "<user mode string>"

         - To answer a query about a client's own mode, RPL_UMODEIS is sent back.

       234    RPL_SERVLIST
              "<name> <server> <mask> <type> <hopcount> <info>"

       235    RPL_SERVLISTEND
              "<mask> <type> :End of service listing"

         - When listing services in reply to a SERVLIST message, a server is required to send the list back using the RPL_SERVLIST and RPL_SERVLISTEND messages.  A separate RPL_SERVLIST is sent for each service.  After the services have been listed (or if none present) a RPL_SERVLISTEND MUST be sent.

       251    RPL_LUSERCLIENT
              ":There are <integer> users and <integer>
               services on <integer> servers"
       252    RPL_LUSEROP
              "<integer> :operator(s) online"
       253    RPL_LUSERUNKNOWN
              "<integer> :unknown connection(s)"
       254    RPL_LUSERCHANNELS
              "<integer> :channels formed"
       255    RPL_LUSERME
              ":I have <integer> clients and <integer>
                servers"

         - In processing an LUSERS message, the server sends a set of replies from RPL_LUSERCLIENT, RPL_LUSEROP, RPL_USERUNKNOWN, RPL_LUSERCHANNELS and RPL_LUSERME.  When replying, a server MUST send back RPL_LUSERCLIENT and RPL_LUSERME.  The other replies are only sent back if a non-zero count is found for them.

       256    RPL_ADMINME
              "<server> :Administrative info"
       257    RPL_ADMINLOC1
              ":<admin info>"
       258    RPL_ADMINLOC2
              ":<admin info>"
       259    RPL_ADMINEMAIL
              ":<admin info>"

         - When replying to an ADMIN message, a server is expected to use replies RPL_ADMINME through to RPL_ADMINEMAIL and provide a text message with each.  For RPL_ADMINLOC1 a description of what city, state and country the server is in is expected, followed by details of the institution (RPL_ADMINLOC2) and finally the administrative contact for the server (an email address here is REQUIRED) in RPL_ADMINEMAIL.

       263    RPL_TRYAGAIN
              "<command> :Please wait a while and try again."

         - When a server drops a command without processing it, it MUST use the reply RPL_TRYAGAIN to inform the originating client.

*** Error replies from RFC document
5.2 Error Replies  - found in the range from 400 to 599.

       401    ERR_NOSUCHNICK
              "<nickname> :No such nick/channel"

          - Used to indicate the nickname parameter supplied to a command is currently unused.

       402    ERR_NOSUCHSERVER
              "<server name> :No such server"

         - Used to indicate the server name given currently does not exist.

       403    ERR_NOSUCHCHANNEL
              "<channel name> :No such channel"

         - Used to indicate the given channel name is invalid.

       404    ERR_CANNOTSENDTOCHAN
              "<channel name> :Cannot send to channel"

         - Sent to a user who is either (a) not on a channel which is mode +n or (b) not a chanop (or mode +v) on a channel which has mode +m set or where the user is banned and is trying to send a PRIVMSG message to that channel.

       405    ERR_TOOMANYCHANNELS
              "<channel name> :You have joined too many channels"

         - Sent to a user when they have joined the maximum number of allowed channels and they try to join another channel.

       406    ERR_WASNOSUCHNICK
              "<nickname> :There was no such nickname"

         - Returned by WHOWAS to indicate there is no history information for that nickname.

       407    ERR_TOOMANYTARGETS
              "<target> :<error code> recipients. <abort message>"

         - Returned to a client which is attempting to send a PRIVMSG/NOTICE using the user@host destination format and for a user@host which has several occurrences.

         - Returned to a client which trying to send a PRIVMSG/NOTICE to too many recipients.

         - Returned to a client which is attempting to JOIN a safe channel using the shortname when there are more than one such channel.

       408    ERR_NOSUCHSERVICE
              "<service name> :No such service"

         - Returned to a client which is attempting to send a SQUERY to a service which does not exist.

       409    ERR_NOORIGIN
              ":No origin specified"

         - PING or PONG message missing the originator parameter.

       411    ERR_NORECIPIENT
              ":No recipient given (<command>)"
       412    ERR_NOTEXTTOSEND
              ":No text to send"
       413    ERR_NOTOPLEVEL
              "<mask> :No toplevel domain specified"
       414    ERR_WILDTOPLEVEL
              "<mask> :Wildcard in toplevel domain"
       415    ERR_BADMASK
              "<mask> :Bad Server/host mask"

         - 412 - 415 are returned by PRIVMSG to indicate that the message wasn't delivered for some reason. ERR_NOTOPLEVEL and ERR_WILDTOPLEVEL are errors that are returned when an invalid use of "PRIVMSG $<server>" or "PRIVMSG #<host>" is attempted.

       421    ERR_UNKNOWNCOMMAND
              "<command> :Unknown command"

         - Returned to a registered client to indicate that the command sent is unknown by the server.

       422    ERR_NOMOTD
              ":MOTD File is missing"

         - Server's MOTD file could not be opened by the server.

       423    ERR_NOADMININFO
              "<server> :No administrative info available"

         - Returned by a server in response to an ADMIN message when there is an error in finding the appropriate information.

       424    ERR_FILEERROR
              ":File error doing <file op> on <file>"

         - Generic error message used to report a failed file operation during the processing of a message.

       431    ERR_NONICKNAMEGIVEN
              ":No nickname given"

         - Returned when a nickname parameter expected for a command and isn't found.

       432    ERR_ERRONEUSNICKNAME
              "<nick> :Erroneous nickname"

         - Returned after receiving a NICK message which contains characters which do not fall in the defined set.  See section 2.3.1 for details on valid nicknames.

       433    ERR_NICKNAMEINUSE
              "<nick> :Nickname is already in use"

         - Returned when a NICK message is processed that results in an attempt to change to a currently existing nickname.

       436    ERR_NICKCOLLISION
              "<nick> :Nickname collision KILL from <user>@<host>"

         - Returned by a server to a client when it detects a nickname collision (registered of a NICK that already exists by another server).

       437    ERR_UNAVAILRESOURCE
              "<nick/channel> :Nick/channel is temporarily unavailable"

         - Returned by a server to a user trying to join a channel currently blocked by the channel delay mechanism.

         - Returned by a server to a user trying to change nickname when the desired nickname is blocked by the nick delay mechanism.

       441    ERR_USERNOTINCHANNEL
              "<nick> <channel> :They aren't on that channel"

         - Returned by the server to indicate that the target user of the command is not on the given channel.

       442    ERR_NOTONCHANNEL
              "<channel> :You're not on that channel"

         - Returned by the server whenever a client tries to perform a channel affecting command for which the client isn't a member.

       443    ERR_USERONCHANNEL
              "<user> <channel> :is already on channel"

         - Returned when a client tries to invite a user to a channel they are already on.

       444    ERR_NOLOGIN
              "<user> :User not logged in"

         - Returned by the summon after a SUMMON command for a user was unable to be performed since they were not logged in.

       445    ERR_SUMMONDISABLED
              ":SUMMON has been disabled"

         - Returned as a response to the SUMMON command.  MUST be returned by any server which doesn't implement it.

       446    ERR_USERSDISABLED
              ":USERS has been disabled"

         - Returned as a response to the USERS command.  MUST be returned by any server which does not implement it.

       451    ERR_NOTREGISTERED
              ":You have not registered"

         - Returned by the server to indicate that the client MUST be registered before the server will allow it to be parsed in detail.

       461    ERR_NEEDMOREPARAMS
              "<command> :Not enough parameters"

         - Returned by the server by numerous commands to indicate to the client that it didn't supply enough parameters.

       462    ERR_ALREADYREGISTRED
              ":Unauthorized command (already registered)"

         - Returned by the server to any link which tries to change part of the registered details (such as password or user details from second USER message).

       463    ERR_NOPERMFORHOST
              ":Your host isn't among the privileged"

         - Returned to a client which attempts to register with a server which does not been setup to allow connections from the host the attempted connection is tried.

       464    ERR_PASSWDMISMATCH
              ":Password incorrect"

         - Returned to indicate a failed attempt at registering a connection for which a password was required and was either not given or incorrect.

       465    ERR_YOUREBANNEDCREEP
              ":You are banned from this server"

         - Returned after an attempt to connect and register yourself with a server which has been setup to explicitly deny connections to you.

       466    ERR_YOUWILLBEBANNED

         - Sent by a server to a user to inform that access to the server will soon be denied.

       467    ERR_KEYSET
              "<channel> :Channel key already set"
       471    ERR_CHANNELISFULL
              "<channel> :Cannot join channel (+l)"
       472    ERR_UNKNOWNMODE
              "<char> :is unknown mode char to me for <channel>"
       473    ERR_INVITEONLYCHAN
              "<channel> :Cannot join channel (+i)"
       474    ERR_BANNEDFROMCHAN
              "<channel> :Cannot join channel (+b)"
       475    ERR_BADCHANNELKEY
              "<channel> :Cannot join channel (+k)"
       476    ERR_BADCHANMASK
              "<channel> :Bad Channel Mask"
       477    ERR_NOCHANMODES
              "<channel> :Channel doesn't support modes"
       478    ERR_BANLISTFULL
              "<channel> <char> :Channel list is full"

       481    ERR_NOPRIVILEGES
              ":Permission Denied- You're not an IRC operator"

         - Any command requiring operator privileges to operate MUST return this error to indicate the attempt was unsuccessful.

       482    ERR_CHANOPRIVSNEEDED
              "<channel> :You're not channel operator"

         - Any command requiring 'chanop' privileges (such as MODE messages) MUST return this error if the client making the attempt is not a chanop on the specified channel.

       483    ERR_CANTKILLSERVER
              ":You can't kill a server!"

         - Any attempts to use the KILL command on a server are to be refused and this error returned directly to the client.

       484    ERR_RESTRICTED
              ":Your connection is restricted!"

         - Sent by the server to a user upon connection to indicate the restricted nature of the connection (user mode "+r").

       485    ERR_UNIQOPPRIVSNEEDED
              ":You're not the original channel operator"

         - Any MODE requiring "channel creator" privileges MUST return this error if the client making the attempt is not a chanop on the specified channel.

       491    ERR_NOOPERHOST
              ":No O-lines for your host"

         - If a client sends an OPER message and the server has not been configured to allow connections from the client's host as an operator, this error MUST be returned.

       501    ERR_UMODEUNKNOWNFLAG
              ":Unknown MODE flag"

         - Returned by the server to indicate that a MODE message was sent with a nickname parameter and that the a mode flag sent was not recognized.

       502    ERR_USERSDONTMATCH
              ":Cannot change mode for other users"

         - Error sent to any user trying to view or change the user mode for a user other than themselves.


* [2025-09-11 jue] Have to understand how poll() works
https://thelinuxcode.com/use-poll-system-call-c/
It looks like we would store all our "clients", open connections whatever and "poll" them to find events (messages) to process...?
* TODO Understand epoll() semantics
According ot the man page there are 2 versions: level-triggered (default, like poll) and edge-triggered (which I don't understand the point of). There's something relating to the EPOLLET flag somewhere here.

[[file:~/Documents/00_WorkInProgress/2023_04_42UrdulizCurso/ft_irc/main.cpp::// - epoll_wait for an event BUT NOTE this blocks the thread, is it forbidden?]]
** [2025-09-16 mar] An epoll() tutorial to read
https://www.oddmeta.net/archives/375.html
** An article on the how and why of epoll https://darkcoding.net/software/epoll-the-api-that-powers-the-modern-internet/
** The important enums of events
These get ||'d together to make the set of what is being polled for
- EINTR
- EAGAIN
- EWOULDBLOCK
- EPOLLIN
  input available to read
- EPOLLOUT
  output available to write?
** What is the epoll_event struct?
- events: what is being listened for (per above)
- data.fd: the file descriptor that the event refers to or occurs on
** epoll_ctl()
Parameters this takes:
- the fd returned by the epoll_create call
- enum of a command, e.g. EPOLL_CTL_ADD
- fd of the thing (socket?) to be listening to.
- pointer to an epoll_event struct
  ...I don't know what that is used for -- the event we are adding?
* [2025-09-20 sáb] If the program crashes, we cannot bind the next time we run it

Something needs to be released or cleared?

[[file:~/Documents/00_WorkInProgress/2023_04_42UrdulizCurso/ft_irc/Server.cpp::std::cout << "Mensaje recibido de fd " << events\[i\].data.fd << ": " << buf << std::endl;]]
* [2025-09-20 sáb] if we need to forcefully unbind a crashed socket
lsof -n -i

Find the process you're looking for and kill it.

From lsof manual:

    -n This option inhibits the conversion of network numbers to host names for network files. Inhibiting conversion may make lsof run faster. It is also useful when host name lookup is not working properly.

    -i [i] This option selects the listing of files any of whose Internet address matches the address specified in i. If no address is specified, this option selects the listing of all Internet and x.25 (HP-UX) network files.


[[file:~/Documents/00_WorkInProgress/2023_04_42UrdulizCurso/ft_irc/Server.cpp::// ...or a place to store it if it is not.]]
* [ ] Sending out non-numeric server replies
Possibly an overload or similar method to Server::_reply
Has to have the same ease of use, but can skip the numeric SWITCH-CASE forest for the parameters. (Although then maybe it needs the if-then matching mess for the parameters...)
* [ ] Overload Server::_reply so it can take a Channel* ?
This would allow the replies to include channel names, and possibly would be good for the needed "list of channels" parameter handling that JOIN and PART (and others?) need.
