#ifndef REPLY_ENUMS_HPP
# define REPLY_ENUMS_HPP
// Here, all the reply codes we use

enum ReplyCodes
{
	RPL_WELCOME		=	1,
    RPL_YOURHOST		=	2,
    RPL_CREATED		=	3,
    RPL_MYINFO 		=	4,
    ERR_UNKNOWNCOMMAND	=	421,
    ERR_NONICKNAMEGIVEN =	431,
    ERR_ERRONEUSNICKNAME= 	432,
    ERR_NICKNAMEINUSE 	=	433,
	ERR_NOTREGISTERED 	=	451,
	ERR_NEEDMOREPARAMS	=	461,
    ERR_ALREADYREGISTERED=	462,
	ERR_PASSWORDMISMATCH=	464
};
#endif
