#ifndef REPLY_ENUMS_HPP
# define REPLY_ENUMS_HPP
// Here, all the reply codes we use

enum ReplyCodes
{
    ERR_UNKNOWNCOMMAND	=	421,
    ERR_NONICKNAMEGIVEN =	431,
    ERR_ERRONEUSNICKNAME= 	432,
    ERR_NICKNAMEINUSE 	=	433,
	ERR_NOTREGISTERED 	=	451,
	ERR_NEEDMOREPARAMS	=	461,
	ERR_PASSWORDMISMATCH=	464
};
#endif
