#ifndef REPLY_ENUMS_HPP
# define REPLY_ENUMS_HPP
// Here, all the reply codes we use

enum ReplyCodes
{
	RPL_WELCOME		=	1,
    RPL_YOURHOST		=	2,
    RPL_CREATED		=	3,
    RPL_MYINFO 		=	4,
	RPL_USERHOST		=	302,
	RPL_UNAWAY			=	305,
	RPL_NOWAWAY		=	306,
	RPL_ENDOFWHO		=	315,
	RPL_LIST			=	322,
	RPL_LISTEND		=	323,
    RPL_TOPIC			=	332,
    RPL_TOPICWHOTIME	=	333,
	RPL_WHOREPLY		=	352,
	ERR_NOSUCHNICK		=	401,
    ERR_NOSUCHCHANNEL	=	403,
	ERR_CANNOTSENDTOCHAN=	404,
	ERR_NOORIGIN		=	409,
    ERR_UNKNOWNCOMMAND	=	421,
    ERR_NONICKNAMEGIVEN =	431,
    ERR_ERRONEUSNICKNAME=	432,
    ERR_NICKNAMEINUSE 	=	433,
	ERR_USERNOTINCHANNEL=	441,
    ERR_NOTONCHANNEL	=	442,
	ERR_NOTREGISTERED 	=	451,
	ERR_NEEDMOREPARAMS	=	461,
    ERR_ALREADYREGISTERED=	462,
	ERR_PASSWORDMISMATCH=	464,
    ERR_INVITEONLYCHAN	=	473,
    ERR_BADCHANMASK	=	476,
	ERR_CHANOPRIVSNEEDED=	482
};
#endif
